---
- name: This play is to create Dockerfile,Build Image and run Docker Container
  hosts: docker
  become: true

  tasks:
     - name: copy files from controller to node
       become: true
       ansible.builtin.copy:
         src: sample25may2022-master
         dest: /home/ansibleadmin

     - name: build an image
       docker_image:
           name: devopslab-image
           path : /home/ansibleadmin/sample25may2022-master
           force: yes
           state: present

     - name: run the container
       docker_container:
           name: devopslab-container
           image: devopslab-image:latest
           state: started
           recreate: yes
           published_ports:
                   - 0.0.0.0:8080:80

...
